### ISSUE TITLE
"active" localized to "inactive"

### ISSUE THREAD

**Issue by unhammer** [the-cavalry/light-locker#104]
https://github.com/the-cavalry/light-locker/blob/489704d5dba2f8ebee85be3e0d87b9e29b5518d8/po/nb.po#L79..L81
flipped a bit (and has a superfluous `This` at the start of the sentence), should probably be:
```
msgstr[0] "Skjermspareren har vært aktiv i %d sekund.\n"
msgstr[1] "Skjermspareren har vært aktiv i %d sekunder.\n"
```

**Comment by tintou** [comment]
Light Locker is translated in Transifex, you can submit your changes here https://www.transifex.com/the_cavalry/light-locker/language/nb/

**Comment by unhammer** [comment]
aha, done :)
