### ISSUE TITLE
light-locker should not always mute audio

### ISSUE THREAD

**Issue by git-madresc** [the-cavalry/light-locker#107]
I understand that for some people it's a great feature to mute audio when light-locker kicks in. However, I would like to opt-out on this. Just as an example: I'm using a softphone on my desktop. This is connected via bluetooth to a headset. Hence, I don't have to sit in front of my computer. It's ok to walk around in the office or sit on a couch. After a few minutes, guess what happens...
So, please, consider to implement a '--no-mute' option.

**Comment by ochosi** [comment]
light-locker locks the complete session, i.e. the seat (in lightdm terms), so there is no way audio could continue to play because it stops all processes of that user session.

Other screensavers (xscreensaver, gnome-screensaver) merely put a black top-level window above all other windows. light-locker completely locks the session and redirects you to the greeter, that's the difference.

**Comment by obadz** [comment]
Is there a way to simulate this 'seat locking' from the command line from a computer that does not have light-locker, for debugging purpose?

**Comment by T-X** [comment]
Hi, generally, in most situations I think this is a great feature, to disable audio when locking. However I also often have the scenario where I would like to be able to continue using audio. My use-case is that I'm in a semi-public, shared space, a club/hackerspace/makerspace. Occasionally I go to our workshop or kitchen in a room next door. Then I would like to lock my screen, but would like to continue listening to music or would like to continue an audio call.

To better comprehend the situation, what does light-locker use to lock a complete session? It's not a SIGSTOP to processes, right? Is it some cgroups feature, does it use something similar to a "systemctl freeze"?

PS: And I also like that light-locker is not just painting a black window. Have had it a few times when using two monitors with gnome-screensaver that when coming back to my desk I'd realize that only one of the two monitors was blackened...
