### ISSUE TITLE
need to enter password twice to unlock

### ISSUE THREAD

**Issue by jamesrobb** [the-cavalry/light-locker#118]
Hello,

I am using light-locker with XFCE, and I notice that often it seems to be the case that I need to enter my password twice to unlock my session. Here is what happens:

1) I lock the screen, and then close my laptop lid
2) I open the lid, enter my password, and then hit enter
3) Instead of being shown my desktop, the screen flickers and I am presented with a login prompt again
4) I enter my password again, then hit enter
5) Finally my desktop is unlocked

I have the suspicion that the laptop is being "double locked". That is, when I lock the screen, and then close the laptop, the laptop is locked again, as I have the configuration option in the power settings set to lock the screen on suspend. I don't know this to be the case, but I could see it being a cause.

How can I go about determining what is going on and how to fix it? I really like light-locker, but I don't think I'd like to use it in the long term if this is the functionality I will have. Ideally I'd like to be able to lock my desktop, and if I choose to suspend it afterwards, I don't wind up in a double lock situation.

Thanks,

**Comment by daniel-barrows** [comment]
This happens to me about 70% of the times that the screen is locked. Not sure what makes the other 30% any different.

This bug has previously been reported by others as well:
* 2016-01-09 https://askubuntu.com/q/718915/396228
* 2018-01-12 https://askubuntu.com/q/994971/396228
* 2018-10-24 https://forum.xfce.org/viewtopic.php?id=12497

**Comment by jamesrobb** [comment]
Closing as this does not seem to have any attention.

**Comment by Photon89** [comment]
@jamesrobb I stumbled upon the same problem. Also there are several people describing it here: https://forum.manjaro.org/t/xfce-has-some-sort-of-double-lockscreen/30491 Is it possible to reopen this? I'd like to try to do some troubleshooting, if you could give some hints on where to start searching.
