### ISSUE TITLE
"terminate" localized as "start" in ru.po

### ISSUE THREAD

**Issue by basinilya** [the-cavalry/light-locker#132]
This is wrong:

	"Inhibit the screensaver from activating. Terminate the light-locker-command "
	"process to end inhibition."
	msgstr "Препятствует активации хранителя экрана. Для отключения выполните процесс light-locker-command"

**Comment by tintou** [comment]
Light Locker is translated in Transifex, can you submit the translation there to avoid conflicts?
https://www.transifex.com/the_cavalry/light-locker/language/ru/

**Comment by basinilya** [comment]
done

**Comment by tintou** [comment]
Fixed in c8a410a4511197093f6d130a55f04dcaf22b1eb0
