### ISSUE TITLE
locker skipped if auto login is enabled for lightdm

### ISSUE THREAD

**Issue by albertnetymk** [the-cavalry/light-locker#143]
After enabling auto login for lightdm, I can still lock the screen using light locker, but once `autologin-user-timeout` times out, I am auto logged in. I was expecting the autologin to come into play on booting up, but not for light-locker locked sessions.

The potential reason may be as specified in this [ticket](https://bugs.launchpad.net/lightdm/+bug/1338727), "I guess it's due to the fact that light locker uses lightdm greeter to lock screen, so when it's displayed, it triggers another autologin timeout."

Some googling found this as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854344

ENV:
lightdm: 1.26
light-locker: 1.8
OS: Debian blueseye

**Comment by tintou** [comment]
It looks like it is an issue with [LightDM](https://github.com/canonical/lightdm) itself and not light-locker. Please open a new issue once lightdm has a way to handle this specific situation and that an action is requires on light-locker side
