### ISSUE TITLE
Light Locker will improperly start XFCE after waking back up and logging in

### ISSUE THREAD

**Issue by 4194304** [the-cavalry/light-locker#167]
When using Light Locker, XFCE will improperly start after logging back into the session when the system is locked. When you log back in, all that can be seen is a black screen and a cursor. No keybinds work within the shell, no terminal, and the only way to fix it is by completely restarting the system.

System:
Arch Linux (latest packages)
LightDM 1.32.0-5
LightDM gtk greeter (latest)
xfce4 (latest)

**Comment by SPK44** [comment]
Did you find a solution to this issue? I am experiencing the same symptoms.
