### ISSUE TITLE
Feature: Run script after unlock

### ISSUE THREAD

**Issue by yforster** [the-cavalry/light-locker#43]
Is there any easy way to run a script after light-locker unlocked the screen again? I'd like to run a command after resume from suspend, but not before my laptop is unlocked.

If it is not possible yet and too much work, can you point me to a suitable part of the code where I can hack it in myself?

Thanks in advance

**Comment by cavalier38** [comment]
You can listen for the dbus lock signal from either logind or consolekit (depending on what you use). You can use dbus-monitor for that. Something like: dbus-monitor "type='signal',sender='org.freedesktop.login1',interface='org.freedesktop.login1.Session'"
This is what light-locker does: in listener_dbus_handle_system_message, see the two checks for signal "Lock".
