### ISSUE TITLE
This is more for my understanding than a bug...

### ISSUE THREAD

**Issue by fredcooke** [the-cavalry/light-locker#46]
On my work box, an ubuntu 14.10 machine, light-locker displays my name and only requires a password. This is what I expect and I'm happy with it.

On this Debian laptop, light-locker displays a login box with both username and password required. The net result is slower re-login, and high chance of typing password into login name out of habit.

Is this me misconfiguring something? Is the debian version just weird? Can I change this behaviour if it's optional?

LXDE + LightDM + LightLocker = win. Thanks for this tool! :-)

**Comment by ochosi** [comment]
That totally depends on which lightdm-greeter you're using and how it is configured. I think for security reasons, Debian uses the greeter in the mode that doesn't display the user-combobox.

So yeah, this is out of light-locker's hands. Best check which greeter you have and how to enable the userlist with it (usually you have to edit a config file).
