### ISSUE TITLE
light-locker changes default DE when the user is changed

### ISSUE THREAD

**Issue by LockeAnarchist** [the-cavalry/light-locker#49]
When I'm using awesomedm, lock the screen and choose another user and log in, the user will start awesomedm instead xfce(default), for example, unless I choose XFCE in the top-right corner.

This is a bug or lightdm doesn't support multiple default sessions, one per user?

**Comment by ochosi** [comment]
I can't imagine how this would be related to light-locker, it only sends the lock-signal to LightDM and doesn't directly interact with the greeter (which is what you're seeing as login/unlock dialog).

And yes, as far as I know, LightDM only supports one systemwide default session, not per-user default sessions.

**Comment by LockeAnarchist** [comment]
Thanks for your answer. I'm using MDM/XScreenSaver now. That's a pity because I love how clean Lightdm/Light-locker is.
