### ISSUE TITLE
Delay screen locking using lid switch

### ISSUE THREAD

**Issue by WyRe** [the-cavalry/light-locker#50]
Hi guys! ... First thank so much for this software... ;P

Second, i would like that i could adjust the delay to lock my screen when i close the lid, for example to 0 seconds ... at least now is about 20 seconds aproximately... (by default, i mean). I have looking for some setup parameter in readme but i think that i don't found anything like.

Anew... Thanks a lot and sorry for post if this is obvious thing xD ...

**Comment by cavalier38** [comment]
Work on this is being done in the lid-closed branch.
If you have a power manager running it might have an option to set the lid action to lock the screen. That could work too.

**Comment by WyRe** [comment]
Same that #68 

Thank you all.
