### ISSUE TITLE
Light-locker bad working

### ISSUE THREAD

**Issue by WyRe** [the-cavalry/light-locker#51]
Greetings! I don't get light-locker working; when i use "light-locker-command -l" screen turns on but i can't restore the session, instead of that, it appear this tty bug: 

http://i.imgur.com/YWDFUAE.jpg

And i can't login or change to other tty. 

These is my lightdm/light-locker packages installed 

local/light-locker 1.6.0-1
    A simple session locker
local/lightdm 1:1.14.0-1
    A lightweight display manager
local/lightdm-gtk-greeter 1:2.0.0-2
    GTK+ greeter for LightDM

I'm running on 3.19.3-1-ARCH 64 bit with XFCE; also i have patched xflock4 to light-locker works. 
Regards and thank so much :D

**Comment by cavalier38** [comment]
Try with dm-tool lock. If that gives the same result it is a problem in lightdm.
You could take a look at the log files in /var/log/lightdm?

**Comment by WyRe** [comment]
Now I am some busy with exam season but when I can I'll try it and inform u, thanks for ur interest. :P

**Comment by WyRe** [comment]
@cavalier38 yes, I get the same issue when I do "dm-tool lock"; so... It does seem an issue with lightdm ... Should I paste /var/log/lightdm content?

**Comment by WyRe** [comment]
@cavalier38 and, I have another question, I'm using Arch and "light-locker-settings" is not in the AUR repos maybe would it be integrated in "light-locker" package? 

And ... Should I post a bug in lightdm bug tracker? 

Thank so much :P

**Comment by cavalier38** [comment]
1) You can look for error in those logs, or post them. Alternatively you could ask this at the lightdm team ;)

2) light-locker-settings is a seperate project developed by the xubuntu team. I'm not sue which other distributions package it. Maybe you can report this problem at the project page: https://launchpad.net/light-locker-settings

**Comment by WyRe** [comment]
same that #68 and #50 

Thank you so much.
