### ISSUE TITLE
With logind, light-locker initiates lock after system has suspended, during resume phase

### ISSUE THREAD

**Issue by CameronNemo** [the-cavalry/light-locker#53]
I see a flash of my session, followed by the greeter, when I resume. I believe this is due to the use of PrepareForSleep() signal without an inhibitor delay causing a race condition where the system suspends before light-locker finishes locking.

See http://www.freedesktop.org/wiki/Software/systemd/inhibit/

**Comment by ozzi-** [comment]
I am experiencing the same Problem on Lubuntu 14.10 and 15.04. 
Any ideas on fixing this?

**Comment by cavalier38** [comment]
light-locker spawns the black screen at suspend. But it could be that the driver doesn't update its buffer as it is already suspending. Adding a suspend delay could solve this, I'll look into that.

**Comment by cavalier38** [comment]
Could you try the delay-suspend branch?
This registers with systemd and unlocks when the window map event it received.
If it is possible to test with multiple monitors, that would be great.

**Comment by CameronNemo** [comment]
Yeah I am getting the black screen 3 for 3. Will test more but it looks good.

**Comment by cavalier38** [comment]
Push to master. I'll leave this open for now, in case you find something.

**Comment by cavalier38** [comment]
Closing, I assume you haven't found anything in the last 2 years.
