### ISSUE TITLE
Apply button cannot be selected by tabbing

### ISSUE THREAD

**Issue by KlongDor** [the-cavalry/light-locker#60]
The apply button in the options menu cannot be selected by tabbing. This is a problem at very low resolutions where the button goes outside the screen and becomes unreachable. It cannot be selected with the arrow keys either

**Comment by ochosi** [comment]
I'm not sure what you are referring to exactly. There are practically no UI elements in light-locker.

Are you maybe referring to light-locker-settings? If so, please report the bug there - thanks!
https://bugs.launchpad.net/light-locker-settings

**Comment by KlongDor** [comment]
Ok thanks
