### ISSUE TITLE
light-locker blanks screen when invoked but shows no password prompt (on NixOS)

### ISSUE THREAD

**Issue by obadz** [the-cavalry/light-locker#66]
Trying to package light-locker for NixOS.  I'm invoking light-locker and get the following warnings:

```
$ light-locker

(process:26627): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion 'source != NULL' failed

** (process:26627): WARNING **: Schema "apps.light-locker" not found. Not storing runtime settings.

** (.light-locker-wrapped:26627): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```

then I call `light-locker-command -l`. It blanks the screen as expected, however no amount of keyboard input makes a prompt show up. Typing password in the dark and pressing enter does not work either.

I'm using XFCE 4.12.1.

In case it can shed some light, here's the package file: https://github.com/obadz/nixpkgs/blob/67c0861c527da6f5d088ddf28435e16fb3368152/pkgs/misc/screensavers/light-locker/default.nix

**Comment by ochosi** [comment]
You need to use light-locker in combination with LightDM. This display manager comes with different greeters (unity-greeter, lightdm-gtk-greeter etc) which will then manage the login and unlocking.

light-locker itself does not provide an unlock dialog.

**Comment by obadz** [comment]
I am using lightDM as well.  How does lightlocker talk to lightDM, does it expect to find certain executables in path?

**Comment by ochosi** [comment]
It tells LightDM to lock the session by sending a DBus message, then LightDM will spawn a new greeter on the next TTY. So in case you had your open session running on TTY7, it will spawn a greeter on TTY8. If you try to get back to your session simply by pressing Ctrl+Alt+F7 you'll see that light-locker blocks access to your session, so you have to authenticate via the greeter.
