### ISSUE TITLE
Display is off after hibernate with lid switch

### ISSUE THREAD

**Issue by WyRe** [the-cavalry/light-locker#68]
I'm not sure if that issue is related with lightdm, light-locker or xfce4-power-manager, but if I set the lid switch to hibernate the system, when I resume from hibernate state (having used the lid, obviously) the display remains turn off. However, if I resume the system from suspend (also having used the lid) doesn't. 

I don't know what could be causing that issue but I guess is related with the fact of lid switch turn off the display before goes to hibernation and the system cannot turn on again the display in resume stage.

Thank you so much, and sorry whether this not the appropriate place to write this.

**Comment by rapgro** [comment]
light-dm shouldn't touch power management. Do you use systemd or some other power manager, what desktop environment?

**Comment by WyRe** [comment]
XFCE, but light-locker or xfce4-power-manager don't "manage" systemd?

**Comment by rapgro** [comment]
xfce4-power-manager does not interact with light-locker but inhibits systemd/logind from taking action and has its own internal logic. What happens when you disable or remove xfpm4?
I doubt light-locker (or systemd itself) has anything to do with your issue.

**Comment by WyRe** [comment]
When I remove (uninstall, and removing xfce4-power-manager category from xfce4-settings-editor) xfpm4 and I setup logind.conf to hibernate with lid switch, the result is exactly the same... Lid switch turn off the display and in resume stage from hibernation the system cannot turn on ... However when I resume from suspend, it doesn't happen and system does turn on the display.

Besides ... logind does not distinguish among HandleLidSwitch and HandleLidSwitchDocked (obviously I have restarted the logind service when I've done changes) always uses HandleLidSwitch setup ... I don't know what can be happening It's so similar to that bug, https://bugzilla.xfce.org/show_bug.cgi?id=12088 but it is in xfpm4 does not in systemd/logind ... Which package, do you suggest, could be causing this?

**Comment by rapgro** [comment]
Not sure about the component. You should better try to ask in the Xfce bug or forum.
https://forum.xfce.org/viewforum.php?id=4

**Comment by WyRe** [comment]
The issue is near to be deprecated, thank you for your interest.
