### ISSUE TITLE
Light locker invocation turns on screen

### ISSUE THREAD

**Issue by Vivalalinux** [the-cavalry/light-locker#69]
Hello!
On my Debian Jessie system with awesome (no DE) I face the following problem:
I use lightdm and light-locker as a screenlocker (both versions 1.4.0 and 1.6.0 tested). If I launch it with "--no-late-locking", then if my display turns of (Xorg settings) session only gets locked when it turns on again, and so I can press some key on the keyboard, and it will be handled before locker turns on -> insecure.

If I launch it without "--no-late-locking", then the following happens:
Computer stands idle for 10 minutes, display turns off, screen locker turns on, display turns back on automatically, wait another 10 minutes for display to turn off again. Embarrassing...

Could you please give a piece of advice of how to get smooth and secure behaviour in this case?
Thank you very much.

**Comment by rapgro** [comment]
I can confirm this with Fedora 22 Cinnamon, but no Light-Locker and LightDM only used here. So this issue must have to do with LightDM itself.

**Comment by Vivalalinux** [comment]
Ah, I see.
Could you please tell me, which version of lightdm you have in your F22 installation?

**Comment by rapgro** [comment]
cinnamon-2.6.13-10.fc22.x86_64
lightdm-1.10.5-4.fc22.x86_64

**Comment by Vivalalinux** [comment]
I also have 1.10 in my Debian.
I have just backported 1.16.2 from Debian Testing. Later I will be able to tell you, if it fixes this problem

**Comment by Vivalalinux** [comment]
Painful to realize, but in 1.16.2 it also reproduces. Gonna file a report for lightdm dev.

**Comment by Vivalalinux** [comment]
https://bugs.launchpad.net/lightdm/+bug/1505757
