### ISSUE TITLE
Background disappears on the lock screen

### ISSUE THREAD

**Issue by terrakok** [the-cavalry/light-locker#86]
On the lock screen (exit from standby mode) instead of desktop images displayed standard background.
If you change the user and back, the background is displayed as it should.
Xubuntu 16.04.1 
XFCE 4.12
light-locker 1.7.0

**Comment by cavalier38** [comment]
light-locker isn't supposed to have effect on the background. Maybe the VT switching interferes with xfdesktop.
Could you try without light-locker? Although this might not switch to the greeter after suspend.
And try with --no-lock-on-suspend? Which will probably give the same results as above.
