### ISSUE TITLE
Cannot start when unity-settings-daemon or gnome-settings-daemon are already running

### ISSUE THREAD

**Issue by nazar-pc** [the-cavalry/light-locker#87]
I'm on development version of Ubuntu 16.04.
I have custom session with Compiz and gnome-settings-daemon (currently).
The problem is that I can't start light-locker if gnome-settings-daemon is already running:
```
[gs_debug_init] gs-debug.c:106 (03:31:14):	 Debugging enabled
[main] light-locker.c:142 (03:31:14):	 initializing light-locker 1.7.0
[main] light-locker.c:144 (03:31:14):	 lock after screensaver 5
[main] light-locker.c:145 (03:31:14):	 late locking 0
[main] light-locker.c:146 (03:31:14):	 lock on suspend 1
[main] light-locker.c:147 (03:31:14):	 lock on lid 0
[main] light-locker.c:148 (03:31:14):	 idle hint 0
[query_session_id] gs-listener-dbus.c:2088 (03:31:14):	 org.freedesktop.login1.NoSessionForPID raised:
 PID 9930 does not belong to any known session


[init_session_id] gs-listener-dbus.c:2180 (03:31:14):	 Got session-id: (null)
[query_sd_session_id] gs-listener-dbus.c:2164 (03:31:14):	 Couldn't determine our own sd session id: Немає такого пристрою чи адреси
[init_session_id] gs-listener-dbus.c:2185 (03:31:14):	 Got sd-session-id: (null)
[init_seat_path] gs-listener-dbus.c:2262 (03:31:14):	 Got seat: /org/freedesktop/DisplayManager/Seat0
[gs_listener_delay_suspend] gs-listener-dbus.c:449 (03:31:14):	 Delay suspend

** (light-locker:9930): WARNING **: screensaver already running in this session
```

An issue seems related to #54, but debug output is different.

I'm using LightDM of course, using Unity greeter. And gnome-screensaver works fine both with u-s-d and g-s-d.
What can I do to find out why it doesn't work and fix it?

**Comment by nazar-pc** [comment]
For `ight-locker` to work it is necessary to turn off screensaver proxy plugin of `gnome-settings-daemon` in dconf.
`active` key needs to be set to `false` at `org.gnome.settings-daemon.plugins.screensaver-proxy` and `gnome-settings-daemon` needs to be restarted.

I'm wondering however, why `light-locker` can't integrate there as well...

**Comment by AlexWayfer** [comment]
> active key needs to be set to false at org.gnome.settings-daemon.plugins.screensaver-proxy and gnome-settings-daemon needs to be restarted.

I can't find this now…
