### ISSUE TITLE
can only lock using light-locker-command -l

### ISSUE THREAD

**Issue by pimvullers** [the-cavalry/light-locker#9]
I can lock my system using light-locker-command -l. But the CTRL-ALT-L shortcut I always used with gnome-screensaver does no longer work, nor does locking from the session-indicator.

**Comment by quequotion** [comment]
Unless the dbus service is named "org.gnome.ScreenSaver", light-locker isn't much use in DEs that rely on gnome-settings-daemon to manage the keyboard shortcut. It's also unusable by indicator-session, which provides a mouseclick menu option to lock the screen in several gnome-derivative DEs.

The problems with gnome-settings-daemon and indicator-session cannot be resolved by changing they key combo (which is now "super+l") or specifying a new key combo to call light-locker (a workaround that does nothing for indicator-session).

In order for gnome-derivative DEs to use light-locker on the default keyboard shorcut, one of two source-code changes must happen:
A: light-locker is patched to provide org.gnome.ScreenSaver.Lock()
B: gnome-settings-daemon is patched to call org.freedesktop.ScreenSaver.Lock()
In order for indicator-session to use light-locker by selecting "Lock..." from the menu one of two source-code changes must happen:
A: light-locker is patched to provide org.gnome.ScreenSaver.Lock()
B: indicator-session is patched to call org.freedesktop.ScreenSaver.Lock()

Although I wouldn't mind seeing DE-independent, debranded forks of both gnome-settings-daemon and indicator-session, the path of least resistance is obviously option A.

**Comment by ochosi** [comment]
The 1.6 release actually provides that feature and should work out of the box with gnome-settings-daemon (and even KDE).

**Comment by quequotion** [comment]
Good to hear!
