### ISSUE TITLE
light-locker doesn't respect screen brightness

### ISSUE THREAD

**Issue by jdeluyck** [the-cavalry/light-locker#91]
On my Dell XPS13, running Debian Sid, light-locker is enabled by default using the XFCE desktop environment.

Unfortunately, light-locker will reset the brightness of the screen to maximum when presenting the greeter/unlocking the screen.

**Comment by mialwe** [comment]
Had the same issue with Debian Jessie and Stretch. Seems to be solved by using `--late-locking`. Tested via manually installed light-locker-settings but this should work without light-locker-settings by just using `Exec=light-locker --lock-after-screensaver=1 --lock-on-suspend --late-locking` in  ~/.config/autostart/light-locker.desktop, too.

**Comment by jdeluyck** [comment]
Thanks, that works!
