### ISSUE TITLE
light-locker forces me to wait when switching between alternate users

### ISSUE THREAD

**Issue by foresto** [the-cavalry/light-locker#94]
I frequently use my desktop's "switch user" feature to start X sessions with different accounts, and switch between them using the Control+Alt+Fx key combination. When I attempt switch back to my original session, Light Locker forces me to wait at a useless "you will be redirected to the unlock dialog" message for about ten seconds before it allows me to get on with it. This continual waste of my time is very annoying.

**Comment by foresto** [comment]
After identifying the hard-coded ten second delay in the code, I was considering writing a patch for this behavior, but it seems someone else beat me to it: PR #93

**Comment by cavalier38** [comment]
See #93
