### ISSUE TITLE
Immediate crash after startup

### ISSUE THREAD

**Issue by hobarrera** [the-cavalry/light-locker#95]
light-locker crashes immediately when trying to run it:

```
$ light-locker --debug
[gs_debug_init] gs-debug.c:106 (22:11:33):       Debugging enabled
[main] light-locker.c:126 (22:11:33):    initializing light-locker 1.6.0
[main] light-locker.c:128 (22:11:33):    lock after screensaver 5
[main] light-locker.c:129 (22:11:33):    late locking 0
[main] light-locker.c:130 (22:11:33):    lock on suspend 1
[init_session_id] gs-listener-dbus.c:1882 (22:11:33):    Got session-id: /org/freedesktop/login1/session/c1
[init_session_id] gs-listener-dbus.c:1887 (22:11:33):    Got sd-session-id: c1
process 4484: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file dbus-message.c line 1367.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
[1]    4484 abort (core dumped)  light-locker --debug
```

I'm using light-locker 1.6.0 on ArchLinux.

**Comment by cavalier38** [comment]
Most probable cause, environment variable XDG_SESSION_PATH isn't set. This should be set by LightDM.

**Comment by hobarrera** [comment]
`XDG_SESSION_PATH` is unset. Is there some spec or documentation explaining what it is?

**Comment by cavalier38** [comment]
This variable is set by ligtdm (which is the required display manager (login manager) for light-locker).
I couldn't find a list of all environments variables it sets but it is in the NEWS file:
http://bazaar.launchpad.net/~lightdm-team/lightdm/trunk/view/2484/NEWS#L814

**Comment by hobarrera** [comment]
I'm not using `light-locker` though.

Anyway, I'm capable of setting `XDG_SESSION_PATH` myself, but I can't find any documentation for it; do you have a link to the spec that defines it? That NEWS doesn't really say anything about it.

**Comment by cavalier38** [comment]
I don't think there exists documentation for this variable. It isn't meant to be set manually.
This environment variable points to the freedesktop DBus interface path for the current session.
LightDM sets this variable:
http://bazaar.launchpad.net/~lightdm-team/lightdm/trunk/view/2484/src/display-manager-service.c#L440

**Comment by hobarrera** [comment]
This sound kinda of redundant, given that [`XDG_SESSION_ID`](https://www.freedesktop.org/software/systemd/man/pam_systemd.html) already contains the current session. The session can also trivially be obtained with [`sd_pid_get_session`](https://www.freedesktop.org/software/systemd/man/sd_pid_get_session.html)

Maybe one of those can be used instead to remove reliance on lightdm's internals?

**Comment by cavalier38** [comment]
These are not the same sessions. XDG_SESSION_ID is the systemd session, same goes for sd_pid_get_session. light-locker doesn't require systemd, ConsoleKit can be used aswell.
For light-locker it is completely valid to rely on LightDM variables as light-locker is "A simple session-locker for lightdm"

**Comment by hobarrera** [comment]
Oh, okay. I assumed that it was integrated to work nicely with `lightdm`, not that it was a strict run-time dependency.

Since I don't use a shared computer, lightdm doesn't really add any value for me, so that's a no-go. Thanks for the support though. :)

Not sure if I should close this or not -- I do think that the output in the initial bug report could be improved (eg: show an clearer error message), but I'll leave that up to you.

**Comment by cavalier38** [comment]
Good to clear that up. The light-locker project was specifically setup for lightdm, as there wasn't a lock screen include, nor do other locker respond to it. This is needed for lightdm user switching.

If you don't use user switching, there are multiple screen lockers out there. They mostly differ in the way you can unlock the screen. And this don't have the negative effects of VT switching, used by lightdm. Pick the one you like ;)

I close this issue. There is another issue about improving the output on this error, and there is a change for that pushed to master.

**Comment by hobarrera** [comment]
Thanks!
