### ISSUE TITLE
Black screen after unlocking automatic locked session with Lightdm 1.22

### ISSUE THREAD

**Issue by HeikoAdams** [the-cavalry/light-locker#98]
After unlocking a session (automaticly) locked with `light-locker-command --lock` the screen is black and the only way to get the desktop back is to reboot the system. Unlocking a session locked with `dm-tool lock` works fine.

Lightdm is at 1.22 and light-locker is at 1.7.0

**Comment by cavalier38** [comment]
You mean that it won't show the login screen?

Are you using a distribution package, or building from source?
In case of the later, if could be that it didn't compile with systemd.
Can you build latest git master?
In either case, can you run light-locker --debug > light-locker.log 2>&1
And also check the log files of lightdm and Xorg?

**Comment by HeikoAdams** [comment]
I'm using a distribution package and it is fixed there in the meantime.
